server:
  port: 8083
spring:
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        connection:
          dialect: org.hibernate.dialect.PostgreSQL95Dialect
  datasource:
    password: 123123
    username: shopUser
    url: jdbc:postgresql://localhost:5430/ShopDB
    driver-class-name: org.postgresql.Driver
