import org.springframework.boot.gradle.plugin.SpringBootPlugin

plugins {
    id 'java'
    id 'org.springframework.boot' version '3.2.1' apply false
    id 'io.spring.dependency-management' version '1.1.4'
}

allprojects {
    group = 'by.zherko'
    version = '0.0.1-SNAPSHOT'

    repositories {
        mavenCentral()
        mavenLocal()
    }
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'io.spring.dependency-management'

    java {
        sourceCompatibility = '17'
    }

    ext {
        springBootVersion = '3.2.1'
        postgresqlVersion = '42.7.1'
        h2Version = '2.2.220'
        lombokVersion = '1.18.30'
        mapstructVersion = '1.5.3.Final'
        lombokMapstructBindingVersion = '0.2.0'
        commonsCollections4Version = '4.4'
        commonsLang3Version = '3.13.0'
        validationApiVersion = '2.0.1.Final'
        hibernateValidatorVersion = '8.0.1.Final'
        jjwtVersion = '0.12.3'
        flywayVersion = '9.22.3'
        springCloudVersion = '2023.0.0'
    }

    configurations {
        compileOnly {
            extendsFrom annotationProcessor
        }
    }

    dependencyManagement {
        imports {
            mavenBom SpringBootPlugin.BOM_COORDINATES
            mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
        }
    }

    dependencies {
        // Common starters
        implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
        implementation 'org.springframework.boot:spring-boot-starter-web'
        implementation 'org.springframework.boot:spring-boot-starter-validation'

        // Utils
        compileOnly "org.projectlombok:lombok:${lombokVersion}"
        annotationProcessor "org.projectlombok:lombok:${lombokVersion}"

        implementation "org.mapstruct:mapstruct:${mapstructVersion}"
        annotationProcessor "org.projectlombok:lombok-mapstruct-binding:${lombokMapstructBindingVersion}"
        annotationProcessor "org.mapstruct:mapstruct-processor:${mapstructVersion}"

        implementation "org.apache.commons:commons-collections4:${commonsCollections4Version}"
        implementation "org.apache.commons:commons-lang3:${commonsLang3Version}"

        // Database
        runtimeOnly "org.postgresql:postgresql:${postgresqlVersion}"

        // Validation
        implementation "javax.validation:validation-api:${validationApiVersion}"
        implementation "org.hibernate:hibernate-validator:${hibernateValidatorVersion}"

        // Test
        testImplementation 'org.springframework.boot:spring-boot-starter-test'
        testImplementation 'org.springframework.security:spring-security-test'
        testRuntimeOnly "com.h2database:h2:${h2Version}"
    }

    tasks.named('test') {
        useJUnitPlatform()
    }
}

tasks.register('publishStarters') {
    group = 'cab-custom-tasks'
    description = 'Publishes starters to local maven repository'

    dependsOn {
        subprojects.findAll { it.name.endsWith('-starter') }
                .collect { it.tasks.named('publishToMavenLocal') }
    }
}

tasks.register('buildBootJars') {
    group = 'cab-custom-tasks'
    description = 'Builds bootJars for whole application'

    dependsOn("publishStarters")

    dependsOn {
        subprojects.findAll {
            it.name.endsWith('-service') ||
                    it.name.endsWith('-gateway') ||
                    it.name.endsWith('-server')
        }.collect { it.tasks.named('bootJar') }
    }
}