version: '3.8'

services:
  main-postgresql:
    image: 'postgres:14.3-alpine'
    container_name: shop-main-db
    restart: always
    ports:
      - "5430:5432"
    environment:
      POSTGRES_USER: shopUser
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: ShopDB
  #product-service
  product-service:
    restart: on-failure
    container_name: Product-module
    ports:
      - "8081:8081"
    build:
      context: /AdminBLService
      dockerfile: Dockerfile
    depends_on:
      - main-postgresql
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://main-postgresql:5432/ShopDB
      SPRING_DATASOURCE_USERNAME: shopUser
      SPRING_DATASOURCE_PASSWORD: 123123
  #user-service
  user-service:
    restart: on-failure
    container_name: User-module
    ports:
      - "8082:8082"
    build:
      context: /UserBlService
      dockerfile: Dockerfile
    depends_on:
      - main-postgresql
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://main-postgresql:5432/ShopDB
      SPRING_DATASOURCE_USERNAME: shopUser
      SPRING_DATASOURCE_PASSWORD: 123123
  #order-service
  order-service:
    restart: on-failure
    container_name: Order-module
    ports:
      - "8083:8083"
    build:
      context: /OrderBLService
      dockerfile: Dockerfile
    depends_on:
      - main-postgresql
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://main-postgresql:5432/ShopDB
      SPRING_DATASOURCE_USERNAME: shopUser
      SPRING_DATASOURCE_PASSWORD: 123123
  # main-service
  main-service:
    restart: on-failure
    container_name: main-module
    ports:
      - "8080:8080"
    build:
      context: /MainModule
      dockerfile: Dockerfile
    environment:
      APP_CLIENTS_ADMIN_NAME: forAdmin-feign
      APP_CLIENTS_ADMIN_URL: product-service:8081
      APP_CLIENTS_ADMIN_PRODUCT-PATH: /v1/products

      APP_CLIENTS_USERS_NAME: user-feign
      APP_CLIENTS_USERS_CART-NAME: cart-feign
      APP_CLIENTS_USERS_URL: user-service:8082
      APP_CLIENTS_USERS_PRODUCT-PATH: /v1/users
      APP_CLIENTS_USERS_CART-PATH: /v1/users/carts

      APP_CLIENTS_ORDERS_NAME: order-feign
      APP_CLIENTS_ORDERS_URL: order-service:8083
      APP_CLIENTS_ORDERS_PRODUCT-PATH: /v1/orders

      SPRING_DATASOURCE_URL: jdbc:postgresql://main-postgresql:5432/ShopDB
      SPRING_DATASOURCE_USERNAME: shopUser
      SPRING_DATASOURCE_PASSWORD: 123123
    depends_on:
      - main-postgresql
      - order-service
      - product-service
      - user-service
