server:
  port: 8080
  tomcat:
    max-http-response-header-size: 1MB
spring:
  jackson:
    serialization:
      fail-on-empty-beans: false
  mvc:
    hidden-method:
      filter:
        enabled: true
    view:
      prefix: /templates/
      suffix: .html
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        connection:
          dialect : org.hibernate.dialect.PostgreSQL95Dialect
  datasource:
    password: 28072004
    username: postgres
    url: jdbc:postgresql://localhost:5432/course_work
  cloud:
    openfeign:
      okhttp:
        enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      enabled: true
app:
  clients:
    admin:
      name: forAdmin-feign
      url: 127.0.0.1:8081
      product-path: /v1/products
    users:
      name : user-feign
      cart-name : cart-feign
      url: 127.0.0.1:8082
      user-path : /v1/users
      cart-path : /v1/users/cart
    orders:
      name: order-feign
      url: 127.0.0.1:8083
      path: /v1/orders
project:
  secretKey : assgaasglnsaggasnklgsankasgnksasnkasgknsdhnasgjahsgvbasghbnvxbzcnb
logging:
  level:
    root: info