server:
  port: 8081
  tomcat:
    max-http-response-header-size: 5MB
spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    password: 123123
    username: shopUser
    url: jdbc:postgresql://localhost:5430/ShopDB
