DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS images;
DROP TABLE IF EXISTS users_cards;
DROP TABLE IF EXISTS purchases;
DROP TABLE IF EXISTS user_carts;
DROP TABLE IF EXISTS users_favorite_products;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS products;