plugins {
    id 'org.springframework.boot'
}

dependencies {
    // Security dependencies specific to user service
    implementation 'org.springframework.boot:spring-boot-starter-security'

    // JWT dependencies
    implementation "io.jsonwebtoken:jjwt-jackson:${jjwtVersion}"
    implementation "io.jsonwebtoken:jjwt-impl:${jjwtVersion}"
    implementation "io.jsonwebtoken:jjwt-api:${jjwtVersion}"

    // Custom starter
    implementation "by.meshicage:application-exception-starter:0.0.2"
}