server:
  port: 8082
  tomcat:
    max-http-response-header-size: 5MB
spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        connection:
          dialect: org.hibernate.dialect.PostgreSQL95Dialect
  datasource:
    password: 28072004
    username: postgres
    url: jdbc:postgresql://localhost:5432/course_work
project:
  secretKey : assgaasglnsaggasnklgsankasgnksasnkasgknsdhnasgjahsgvbasghbnvxbzcnb