server:
  port: 8082
spring:
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        connection:
          dialect: org.hibernate.dialect.PostgreSQL95Dialect
  datasource:
    password: 28072004
    username: postgres
    url: jdbc:postgresql://localhost:5432/course_work
project:
  secretKey : assgaasglnsaggasnklgsankasgnksasnkasgknsdhnasgjahsgvbasghbnvxbzcnb